"""create exploration plans and guide cards

Revision ID: 0a9cec9dc9f8
Revises: b88ed65c69db
Create Date: 2026-07-08 23:20:08.280292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a9cec9dc9f8'
down_revision = 'b88ed65c69db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exploration_plans',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('child_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('destination', sa.String(length=120), nullable=False),
    sa.Column('age_group', sa.String(length=16), nullable=False),
    sa.Column('duration', sa.String(length=32), nullable=False),
    sa.Column('interests', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=24), server_default='draft', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("age_group IN ('3-6', '7-12')", name=op.f('ck_exploration_plans_age_group_allowed')),
    sa.CheckConstraint("status IN ('draft', 'ready', 'in-progress', 'completed')", name=op.f('ck_exploration_plans_status_allowed')),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], name=op.f('fk_exploration_plans_child_id_children'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_exploration_plans_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exploration_plans'))
    )
    with op.batch_alter_table('exploration_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exploration_plans_child_id'), ['child_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exploration_plans_user_id'), ['user_id'], unique=False)

    op.create_table('guide_cards',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('plan_id', sa.BigInteger(), nullable=False),
    sa.Column('child_intro', sa.JSON(), nullable=False),
    sa.Column('questions', sa.JSON(), nullable=False),
    sa.Column('focus_items', sa.JSON(), nullable=False),
    sa.Column('audio_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['exploration_plans.id'], name=op.f('fk_guide_cards_plan_id_exploration_plans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_guide_cards'))
    )
    with op.batch_alter_table('guide_cards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guide_cards_plan_id'), ['plan_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guide_cards')
    op.drop_table('exploration_plans')
    # ### end Alembic commands ###
