"""create users and children

Revision ID: b88ed65c69db
Revises: 
Create Date: 2026-07-08 19:31:28.432597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b88ed65c69db'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('nickname', sa.String(length=50), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('wechat_openid', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('phone IS NOT NULL OR wechat_openid IS NOT NULL', name=op.f('ck_users_has_login_identifier')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_phone'), ['phone'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_wechat_openid'), ['wechat_openid'], unique=True)

    op.create_table('children',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('age', sa.SmallInteger(), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('age_group', sa.String(length=16), nullable=False),
    sa.Column('interests', sa.JSON(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("age_group IN ('3-6', '7-12')", name=op.f('ck_children_age_group_allowed')),
    sa.CheckConstraint('age >= 0 AND age <= 18', name=op.f('ck_children_age_range')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_children_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_children'))
    )
    with op.batch_alter_table('children', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_children_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    pass
