"""create tasks and task submissions

Revision ID: c795c3738e73
Revises: 0a9cec9dc9f8
Create Date: 2026-07-09 18:51:50.536158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c795c3738e73'
down_revision = '0a9cec9dc9f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('plan_id', sa.BigInteger(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('subtitle', sa.String(length=240), nullable=True),
    sa.Column('age_group', sa.String(length=16), nullable=False),
    sa.Column('duration', sa.String(length=32), nullable=False),
    sa.Column('task_type', sa.String(length=32), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('questions', sa.JSON(), nullable=False),
    sa.Column('record_mode', sa.String(length=255), nullable=False),
    sa.Column('theme', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("age_group IN ('3-6', '7-12')", name=op.f('ck_tasks_age_group_allowed')),
    sa.CheckConstraint('sort_order >= 1', name=op.f('ck_tasks_sort_order_positive')),
    sa.ForeignKeyConstraint(['plan_id'], ['exploration_plans.id'], name=op.f('fk_tasks_plan_id_exploration_plans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks')),
    sa.UniqueConstraint('plan_id', 'sort_order', name='plan_sort_order')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_plan_id'), ['plan_id'], unique=False)

    op.create_table('task_submissions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('task_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('in-progress', 'completed')", name=op.f('ck_task_submissions_status_allowed')),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_task_submissions_task_id_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_submissions'))
    )
    with op.batch_alter_table('task_submissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_submissions_task_id'), ['task_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_submissions')
    op.drop_table('tasks')
    # ### end Alembic commands ###
